# Generated by Django 5.1.1 on 2024-10-16 09:50

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cover_image',
            field=models.ImageField(default=1, upload_to=core.models.user_directory_path),
            preserve_default=False,
        ),
    ]
